.expo/packager-info.json
app/screens/authors/AuthorDetail.js
package-lock.json
package.json

Implemented swipe functionality with buttons

Author detail updates

---

app/config/router.js
app/screens/styles/header.js
app/screens/styles/headlines.js
app/screens/styles/search.js
index.js

Fix gap at the top and the bottom on new iPhones

---

app/screens/map/Map.js
package-lock.json
package.json

- Displays articles tagged with location once user clicks on marker
- Deleted follow button; replaced with "close tab" button

Implement article fetching, delete follow button

---

app/assets/constants.js
app/screens/map/Map.js

- switch to prod endpoint url
- map: fix a small bug related to when markers returned is empty

fix: switch to prod endpoint url

---

app/screens/map/Map.js

Fix map's article list view topbar bug for non-iPhone X devices 

---

app/screens/FollowInfoStorage.js

Using [async-storage](https://docs.expo.io/versions/latest/react-native/asyncstorage/#getallkeys)
Functions:
- followCategory(category_id)
- unfollowCategory(category_id)
- followAuthor(author_id)
- unfollowAuthor(author_id)
- isFollowingCategory(category_id)
- isFollowingAuthor(author_id)

Created functions to access follow information locally

---

app/screens/FollowInfoStorage.js

Created updateBackend() function to update the REST API according to the user's updated push notification preferences.

Connecting user's push notification/following preferences to backend using REST API

---

App.js
README.md
app.json
app/helper/NavigationService.js
app/helper/PushNotification.js
index.js

Setup push notification related features

---

app/screens/Headlines.js

- removed alerts when notification settings change
- preloaded notification setting data

Removed alerts when notification settings change

---

CHANGELOG.md
app.json
package.json

These were needed for release.

Release notes

---

CHANGELOG.md
app.json

- Bump version codes
- Fix notification icon on Android
- Update changelog

PN 1.2 release code

---

app/screens/Headlines.js

Show notification popup only once, 

---

app/screens/Headlines.js

Fix #200.
I can't believe there was code here that said `this.state.loading = true;`

Fix loading of articles in Headlines

---

app/screens/authors/AuthorList.js
app/screens/authors/NestedListView.js

- Fix #198 by using React.PureComponent and rendering 1000 items at a time at first
- Add loading icon to authors list page

Fix authors lag

---

app/HTML.js
app/screens/Headlines.js
app/screens/Post.js
app/screens/SettingsPage.js
app/screens/styles/header.js
app/screens/styles/headlines.js

- Updated design of notifications screen to fit with rest of app
- Changed ToggleSwitch components (don't work) to React Native Switch components (need to be tested)
#239

Update notifications modal design, change switches

---

.babelrc
app/assets/constants.js
app/config/router.js
app/screens/Community.js
app/screens/Headlines.js
app/screens/Post.js
app/screens/Tips.js
app/screens/common/Card.js
app/screens/common/card-row.js
app/screens/common/column.js
app/screens/styles/card-style.js
app/screens/styles/column-style.js
app/screens/styles/community.js
app/screens/styles/headlines.js
app/screens/styles/newsfeeditem.js
app/screens/styles/post.js
package-lock.json
package.json
yarn.lock

- Updated the satire section to have salmon background
- Might have actually fixed the height thing for the column layout
- Moved the Spotify and YouTube buttons to the bottom
- Added the indicator dots and made them tappable
- Added grid of links to Community tab.

Updated home layout and Community tab links.

---

app/assets/constants.js
app/config/router.js
app/screens/Author.js
app/screens/Headlines.js
app/screens/Post.js
app/screens/common/Card.js
app/screens/common/newsfeed-item.js
app/screens/styles/column-style.js
app/screens/styles/post.js
package-lock.json
package.json

There are still a few glitches, but now users can tap on the names of authors and view their author pages. This works for articles with multiple authors or one.

Addition of author page

---

app/config/router.js
app/screens/Community.js
app/screens/Headlines.js
app/screens/Tips.js
package-lock.json

Through a `WebView` the donations and tips pages can be displayed in the app.

Donations and tips now are housed in the app.

---

app/config/router.js
app/screens/Headlines.js
app/screens/Search.js
app/screens/common/header.js
app/screens/styles/header.js
app/screens/styles/search.js
package-lock.json

The search function works by calling the WordPress search API endpoint. It is pretty glitchy and does not have great style, but it could work for now.

Preliminary search implementation.

---

app/config/router.js
app/screens/Post.js
app/screens/common/header.js
index.js
package-lock.json
package.json
yarn.lock

Updated article view to look more like the original designs.

Updated article view.

---

README.md
components/Card.js
screens/Home.js

Not all the images are coming into the app with file URLs, causing lots more caution to be of necessity. How strange.

It is fixed for now; back end might have a problem

---

App.js
components/CategoryHeader.js
helpers/wpapi.js
screens/Category.js
screens/Home.js
screens/Post.js

Automatically loads more articles when you get to the bottom of the `FlatList`. Functionality and performance are good enough for now.

Infinite scroll

---

screens/Post.js

[Please describe them here]
[If this is related to existing tickets, include links to them as well ("fixes #[issue number]")]
[If this is a visual change, please add screenshots showing how the app looks like]

photo caption for the media article

---

App.jsx
components/common/Carousel.jsx
components/common/Mark.jsx
components/common/Polyptych.jsx
components/common/Shelf.jsx
components/common/Wildcard.jsx
components/screens/Author.jsx
components/screens/Home.jsx
components/screens/Post.jsx
components/screens/Search.jsx
components/screens/Section.jsx
hooks/useWordPress.js
navigation/LinkingConfiguration.js
utils/constants.js
utils/format.js
utils/model.js

Alt text was previously missing from images displayed in the app, but we’ve now passed that information from our API into the relevant components. Additionally, large components in the UI made from many moving parts have been updated to function more intuitively with VoiceOver. There’s still a lot of work to be done, and we’ve yet to extensively test existing accessibility features for iOS and Android, but hopefully these changes are a step in the right direction. I personally acknowledge that I should have addressed these matters earlier and apologize to those for whom a lack of functionality was a significant hindrance to accessing and interacting with The Daily. Thanks for your patience, and please feel free to open a pull request of your own or send an email to …

Accessibility checks 2023
